apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtalk-bot
  labels:
    app: techtalk-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtalk-bot
  template:
    metadata:
      name: techtalk-bot
      labels:
        app: techtalk-bot
    spec:
      containers:
        - name: techtalk-bot
          image: dantesfoncake/techtalk_bot:latest
          imagePullPolicy: Never
          env:
            - name: TelegramToken
              valueFrom:
                secretKeyRef:
                  name: telegram
                  key: bot_token
            - name: PostgresPassword
              valueFrom:
                secretKeyRef:
                  name: postgres-main-postgresql
                  key: password
            - name: ConnectionStrings__Npsql
              value: "User ID=techtalk_bot;Password=$(PostgresPassword);Host=postgres-main-postgresql.default.svc.cluster.local;Port=5432;Database=techtalk_db"
      restartPolicy: Always
      